<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />




<title>Data Analysis</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-1.1/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-1.1/highlight.js"></script>
<link href="site_libs/font-awesome-4.5.0/css/font-awesome.min.css" rel="stylesheet" />

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs && document.readyState && document.readyState === "complete") {
   window.setTimeout(function() {
      hljs.initHighlighting();
   }, 0);
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}

.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>


<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->




<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
  padding-left: 25px;
  text-indent: 0;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>

<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">assignPOP</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="start.html">Get Started</a>
</li>
<li>
  <a href="analyze.html">Data Analysis</a>
</li>
<li>
  <a href="visualize.html">Result Visualization</a>
</li>
<li>
  <a href="examples.html">Examples</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://github.com/alexkychen/assignPOP">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Data Analysis</h1>

</div>


<p>In this page, we describe how to prepare and import your data sets, whether it is genetic or non-genetic, and how to concatenate genetic and non-genetic data for analyses. We also introduce two resampling cross-validation methods, Monte-Carlo and K-fold cross-validation, to evaluate performance of your baseline or known data, as well as a function to perform an assignment test on unknown individuals using your known data. Lastly, we describe how to identify informative loci when your baseline data has a large number of genetic markers.</p>
<hr />
<div id="prepare-and-import-data" class="section level2">
<h2>Prepare and import data</h2>
<div id="prepare-and-import-genetic-data-of-source-populations" class="section level3">
<h3>Prepare and import genetic data of source populations</h3>
<p>Currently, assignPOP accepts genetic data in GENEPOP format (Rousset 2008<a href="#fn1" class="footnoteRef" id="fnref1"><sup>1</sup></a>), a commonly used format in molecular ecology studies. GENEPOP has two forms, and both forms are accepted by assignPOP. For details about GENEPOP format, please visit <a href="http://genepop.curtin.edu.au/help_input.html" class="uri">http://genepop.curtin.edu.au/help_input.html</a>.</p>
<p>To import a GENEPOP file, use the function <code>read.genpop()</code> and provide a return object name (e.g., <code>genin</code>) as follows.</p>
<pre class="r"><code>genin &lt;- read.genpop( &quot;simGenepop.txt&quot;, pop.names=c(&quot;pop_A&quot;,&quot;pop_B&quot;,&quot;pop_C&quot;) )</code></pre>
<p>The example input file, <a href="https://raw.githubusercontent.com/alexkychen/assignPOP/master/inst/extdata/simGenepop.txt"><em>simGenepop.txt</em></a>, contains <strong>three</strong> simulated populations (or subpopulations) and each population has 30 individuals by 1,000 SNP loci. You can use the argument <code>pop.names</code> to name your populations in your GENEPOP (must follow the group order<a href="#fn2" class="footnoteRef" id="fnref2"><sup>2</sup></a>) so that later you can customize assignment accuracy plots by specifying these names. If <code>pop.names</code> is not provided, pop.<em>NUMBER</em> (e.g., pop.1, pop.2) will be used for the population name.</p>
<p>After importing the file, you should see the following message printed in your R console. Use this information to double check your data was correctly imported.</p>
<pre><code>## ############### assignPOP v1.1 ###############
## 
## A GENEPOP format file was successfully imported!
## 
## DataInfo: 90 obs. by 1000 loci (with 2000 var.)
## DataMatrix: 90 rows by 2001 columns
## Number of pop:3
## Number of inds (pop_A): 30
## Number of inds (pop_B): 30
## Number of inds (pop_C): 30
## 
## Data output in a list comprising the following three elements:
## DataMatrix @ YOUR_LIST_NAME[[1]]
## IndividualNames @ YOUR_LIST_NAME[[2]]
## LocusNames @ YOUR_LIST_NAME[[3]]</code></pre>
</div>
<div id="import-genetic-data-of-unknown-individuals" class="section level3">
<h3>Import genetic data of unknown individuals</h3>
<p>When assigning unknown individuals (see Step 2 in <a href="#analyticalworkflow">Analytical workflow</a>), you will first import a GENEPOP file that includes known individuals (for building predictive models), and then import another GENEPOP that includes unknown individuals. All unknown individuals in your GENEPOP should be saved in one single group, meaning that you will have only one ‘pop’ label in the file. Again, use <code>read.genpop()</code> to import the file and ignore the argument <code>pop.names</code>, but make sure you provide different object names for known and unknown data sets.</p>
<pre class="r"><code># Import a GENEPOP file containing unknown individuals
genin_unknown &lt;- read.genpop( &quot;simGenepopX.txt&quot; )</code></pre>
</div>
<div id="remove-low-variance-loci-optional" class="section level3">
<h3>Remove low variance loci (optional)</h3>
<p>For a very large data file (e.g., tens of thousands of loci), you can choose to remove loci that have low variance<a href="#fn3" class="footnoteRef" id="fnref3"><sup>3</sup></a> across the data set in advance of further analyses. The default of variance threshold is 0.95, meaning that any locus with a major allele occurring in over 95% of individuals across all populations will be removed from the data set.</p>
<p>To remove low variance loci, use the following function and provide a new object name (e.g., <code>genin_rd</code>) :</p>
<pre class="r"><code>genin_rd &lt;- reduce.allele(genin, p = 0.95)</code></pre>
<p>After entering the code, R console should print the following message.</p>
<pre><code>## New data matrix has created! :)
## New DataMatrix size: 90 rows by 1387 columns
## 614 columns (alleles) have been removed
## 693 loci remain</code></pre>
<p>In our example, 307 low variance loci<a href="#fn4" class="footnoteRef" id="fnref4"><sup>4</sup></a> were removed, leaving 693 loci in the new data set, which will be used in further analyses.</p>
</div>
<div id="concatenate-genetic-and-non-genetic-data" class="section level3">
<h3>Concatenate genetic and non-genetic data</h3>
<p>A novel feature of the package is that it can integrate genetic and non-genetic data for population assignment tests. After importing your GENEPOP file, you can use the function <code>compile.data()</code> to concatenate a non-genetic data set and the genetic matrix that was returned from either <code>read.genpop()</code> or <code>reduce.allele()</code>. Your non-genetic data should be saved in a .csv file (elements separated by commas) or table-like text file (elements separated by spaces) in which the first column must be sample IDs that match the IDs in your GENEPOP file, and the rest of columns are non-genetic data, whether it is numeric or categorical. If a sample ID exists in only one of the data sets, the individual will be ignored in the new integrated data.</p>
<p>To concatenate data, use the following function and provide a new object name (e.g., <code>comin</code>):</p>
<pre class="r"><code>comin &lt;- compile.data(genin_rd, &quot;morphData.csv&quot;)</code></pre>
<p>The above <a href="https://raw.githubusercontent.com/alexkychen/assignPOP/master/inst/extdata/morphData.csv"><em>morphData.csv</em></a> file has the same individuals as in <a href="https://raw.githubusercontent.com/alexkychen/assignPOP/master/inst/extdata/simGenepop.txt"><em>simGenepop.txt</em></a> and contains 4 numeric variables (morphometric measurements) for each individual. After executing the function, it will prompt the following message and wait for your answer to verify the data type (numeric or categorical).</p>
<pre><code>## Import a .CSV file.
## 4 additional variables detected.
## Checking variable data type...
##  D1.2(integer)  D2.3(integer)  D3.4(integer)  D1.4(integer)</code></pre>
<p>If a variable is categorical, it will automatically convert it to new <a href="https://en.wikipedia.org/wiki/Dummy_variable_(statistics)">dummy variables</a> using <a href="https://stat.ethz.ch/R-manual/R-devel/library/stats/html/model.matrix.html">model.matrix()</a> so that the categorical data can be quantified for further analyses. If your data type was incorrectly identified, simply enter <strong>N</strong> and then follow the prompted dialogue to change your data type. If your data type was correctly identified (entry is <strong>Y</strong> in this example), then it will print the following message.</p>
<pre><code>## New data set created!!
## It has 90 observations by 1391 variables
## including 693 loci(1386 alleles) plus 4 additional variables(4 columns)</code></pre>
<p>If you are evaluating a baseline using integrated data, the return object (e.g., <code>comin</code>) will be used in resampling cross-validation. On the other hand, if you are assigning unknown individuals, be sure to run the function <code>compile.data()</code> for known and unknown data sets, respectively, and provide different return object names. These two objects will be used in the assignment test (<code>assign.X()</code>).</p>
</div>
<div id="prepare-and-import-non-genetic-data" class="section level3">
<h3>Prepare and import non-genetic data</h3>
<p>In addition to analyzing genetic and integrated data, you can perform assignment tests using only non-genetic data. This allows you to compare the results between data types. A non-genetic data set for baseline evaluation should include 1) sample IDs in the first column, 2) population label<a href="#fn5" class="footnoteRef" id="fnref5"><sup>5</sup></a> in the last column, and 3) features in columns between the first and last column. The file should be saved in a .csv (comma delimited) or table-like text file that can be read into R using <code>read.csv()</code> or <code>read.table()</code>. For example, if we are going to perform assignment test using the morphometric data (<a href="https://raw.githubusercontent.com/alexkychen/assignPOP/master/inst/extdata/morphData.csv"><em>morphData.csv</em></a>) alone, we would need to add a population column after the last feature column. It can be done by either manually editing the file or adding a column after the file was imported (as shown below).</p>
<pre class="r"><code>#Import morphometric data containing sample IDs and features
morphdf &lt;- read.csv( &quot;morphData.csv&quot;, header=TRUE )
#Create a string vector for population label (repeat each name for 30 individuals)
pop_label &lt;- c( rep(&quot;pop_A&quot;, 30), rep(&quot;pop_B&quot;, 30), rep(&quot;pop_C&quot;, 30) ) 
#Add the pop_label to the last column; &#39;morphdf_pop&#39; is a data frame with population label in the last column
morphdf_pop &lt;- cbind(morphdf, pop_label)</code></pre>
<p>A non-genetic data containing the population label could be used for baseline evaluation or as a baseline to predict unknown individuals. In other words, when performing an assignment test on unknown individuals using non-genetic data alone, the population column should be included in the known data set but not in the unknown data set.</p>
<hr />
</div>
</div>
<div id="performassignment" class="section level2">
<h2>Perform population assignment</h2>
<p>To evaluate discriminatory power of a baseline, the package uses Monte-Carlo cross-validation (function <code>assign.MC()</code>) to estimate assignment accuracies over all populations and for each population, and uses <em>K</em>-fold cross-validation (function <code>assign.kfold()</code>) to estimate membership probabilities across all individuals. <a href="http://stats.stackexchange.com/questions/51416/k-fold-vs-monte-carlo-cross-validation">About Monte-Carlo and <em>K</em>-fold cross-validation</a></p>
<div id="monte-carlo-cross-validation-for-baseline-evaluation" class="section level3">
<h3>Monte-Carlo cross-validation for baseline evaluation</h3>
<p>When performing Monte-Carlo cross-validation using genetic or integrated data, users can specify multiple proportions or multiple fixed numbers of individuals from each population to be used as training individuals (arg. <code>train.inds</code>) and multiple proportions of loci to be used as training loci (arg. <code>train.loci</code>). A set of training loci can be chosen either randomly (arg. <code>loci.sample=&quot;random&quot;</code>) or based on locus <em>F<sub>ST</sub></em> estimated within training individuals (arg. <code>loci.sample=&quot;fst&quot;</code>). Each combination of training individuals and loci can be resampled multiple times (arg. <code>iterations</code>). For example, the following code performs a total of 360 assignment tests, sampling 50%, 70% and 90% of individuals randomly from each population, using the highest 10%, 25%, 50% of <em>F<sub>ST</sub></em> loci as well as all loci for the training data. Each sample size combination was resampled 30 times.</p>
<pre class="r"><code>assign.MC(genin_rd, train.inds=c(0.5, 0.7, 0.9), train.loci=c(0.1, 0.25, 0.5, 1), 
          loci.sample=&quot;fst&quot;, iterations=30, dir=&quot;Result-folder/&quot;, model=&quot;svm&quot; )</code></pre>
<p>To use certain numbers, rather than proportions, of individuals from each population as training data, enter positive integers in the argument <code>train.inds</code>.</p>
<p>If you are analyzing non-genetic data alone, the arguments, <code>train.loci</code> and <code>loci.sample</code>, will be automatically ignored.</p>
<p>The results will be saved in a folder created via the argument <code>dir</code>. In the above example, a folder named “Result-folder” is created and results are saved in it. You must include a forward slash (/) at the end of your folder name.</p>
<p>In addition, you can use the argument <code>model</code> to select a classifier for prediction. In this case, the <a href="https://en.wikipedia.org/wiki/Support_vector_machine">Support Vector Machine (SVM)</a> classifier is used. Other SVM related arguments, <code>svm.kernel</code> and <code>svm.cost</code>, can be specified to fine tune the predictive model. See the <a href="https://cran.r-project.org/web/packages/e1071/index.html">e1071</a> package for details about SVM. Other classifiers, including <a href="https://en.wikipedia.org/wiki/Linear_discriminant_analysis">LDA</a>, <a href="https://en.wikipedia.org/wiki/Naive_Bayes_classifier">naive Bayes</a>, <a href="https://en.wikipedia.org/wiki/Decision_tree">decision tree</a>, and <a href="https://en.wikipedia.org/wiki/Random_forest">random forest</a>, can be used to build predictive models. Type <code>?assign.MC</code> to see details.</p>
</div>
<div id="k-fold-cross-validation-for-baseline-evaluation" class="section level3">
<h3><em>K</em>-fold cross-validation for baseline evaluation</h3>
<p>While Monte-Carlo cross-validation helps evaluate variation in assignment accuracy through resampling, it does not guarantee that every individual was tested, and multiple tests on an individual also makes it difficult to estimate membership probabilities across individuals and populations. As such, we introduced <em>K</em>-fold cross-validation to help estimate membership probability because it guarantees that every individual will be tested once while none of them will be used as training and test individuals in the same test. To perform <em>K</em>-fold cross-validation, use the following function:</p>
<pre class="r"><code>assign.kfold(genin_rd, k.fold=c(3, 4, 5), train.loci=c(0.1, 0.25, 0.5, 1), 
             loci.sample=&quot;random&quot;, dir=&quot;Result-folder2/&quot;, model=&quot;lda&quot; )</code></pre>
<p>In the <em>K</em>-fold cross-validation, rather than specifying the proportions of individuals to be sampled, use the argument <code>k.fold</code> to specify the number of groups to divide each population into. The above example divides individuals from each population into 3, 4, or 5 groups. Within each fold, 10%, 25% and 50% of random loci (arg. <code>loci.sample = &quot;random&quot;</code>), as well as all loci, were sampled for training data (arg. <code>train.loci</code>). As such, the <em>K</em>-fold cross-validation performs a total of 48 assignment tests (N = (3+4+5)*4 tests).</p>
<p>When analyzing non-genetic data alone, the arguments, <code>train.loci</code> and <code>loci.sample</code>, will be automatically ignored.</p>
<p>To most efficiently compute the analyses, by default, all available cores/threads minus one (N-1) of your computer’s CPU are used for parallel analyses so that multiple assignment tests are performed simultaneously (assuming the computer has a multi-core CPU). To change the number of cores/threads used, simply specify a number in the argument <code>processors</code>.</p>
<p>Depending on the size of your dataset, running <code>assign.MC()</code> may take a few minutes to hours; <code>assign.kfold()</code> is usually quicker because of fewer tests. You can monitor the analysis status by counting the output files in the result folder.</p>
</div>
<div id="assign-unknown-individuals" class="section level3">
<h3>Assign unknown individuals</h3>
<p>In addition to evaluating a known data set, the package also provides a function <code>assign.X()</code> that allows you to perform an assignment test on unknown individuals using the known data that was evaluated (assuming the results are satisfactory). After importing your known and unknown data sets (they should be the same data type and have same feature names), use the arguments <code>x1</code> and <code>x2</code> to specify the known and unknown data, respectively.</p>
<pre class="r"><code># Perform an assignment test using decision tree as the predictive model
assign.X( x1=genin, x2=genin_unknown, dir=&quot;Result-folder3/&quot;, model=&quot;tree&quot;)

# Use `?assign.X` to see other argument settings.</code></pre>
<p>The assignment result will be saved in a text file named <em>AssignmentResult.txt</em> under the designated folder. This file includes sample IDs of your unknown individuals, predicted populations and the probabilities. When the assignment is done, it will prompt a message asking you whether a membership probability plot should be generated. You can enter <strong>Y</strong> to visualize the result right away.</p>
</div>
<div id="pca-for-data-transformation" class="section level3">
<h3>PCA for data transformation</h3>
<p>The assignment functions, <code>assign.MC()</code>, <code>assign.kfold()</code> and <code>assign.X()</code>, use PCA for dimensionality reduction. It converts your independent variables to Principle Components and retain the PCs that have eigenvalues greater than 1 (the Kaiser-Guttman criterion) as new features (arg. <code>pca.PCs=&quot;kaiser-guttman&quot;</code>). Or, you can specify an integer in the argument <code>pca.PCs</code> (e.g., <code>pca.PCs = 10</code>) to choose a specific number of PCs to be retained.</p>
<p>The PCA will always perform on the genetic data, whether you are analyzing genetic-only or integrated data. When analyzing integrated data, you have three options to perform PCA on the data. First, you can perform PCA across all features (set arg. <code>pca.method=&quot;mixed&quot;</code>), meaning that each PC includes information of genetic and non-genetic data. This is default setting. Second, you can perform PCA on genetic and non-genetic data independently (set arg. <code>pca.method=&quot;independent&quot;</code>), meaning that your transformed data includes genetic PCs and non-genetic PCs. Third, you can choose to use original non-genetic data as features without performing PCA on them (set. arg. <code>pca.method=&quot;original&quot;</code>). This option ends up using genetic PCs and original non-genetic data to build predictive models.</p>
<p>When analyzing non-genetic data alone, you can determine whether PCA is performed on the data. You set the argument <code>pca.method=TRUE</code> to perform PCA, or <code>pca.method=FALSE</code> to not perform PCA.</p>
<hr />
</div>
</div>
<div id="accuracy" class="section level2">
<h2>Calculate assignment accuracy</h2>
<p>When the assignment analysis (<code>assign.MC()</code> or <code>assign.kfold</code>) is complete, assignment accuracies can be calculated using the following functions.</p>
<pre class="r"><code>accuMC &lt;- accuracy.MC(dir = &quot;Result-folder/&quot;) #Use this function for Monte-Carlo cross-validation results
accuKF &lt;- accuracy.kfold(dir = &quot;Result-folder2/&quot;) #Use this function for K-fold cross-validation results</code></pre>
<p>These functions read through each assignment result in the designated folder (arg. <code>dir</code>) and calculate the assignment accuracies over all populations and for each population. The results will be saved in a text file (named <strong>Rate_of….txt</strong>) and a returned object if provided (e.g., <code>accuMC</code> and <code>accuKF</code>). This file or object (as a data frame object) will be used to create assignment accuracy plots (described in the next section). If you did not provide a returned object or if you want to read the data from the text file later on, simply use the <code>read.table()</code> function to import the data into R.</p>
<pre class="r"><code>accuMC &lt;- read.table(&quot;Rate_of....txt&quot;, header=T)</code></pre>
<p>Because Monte-Carlo cross-validation is designed for evaluating assignment accuracy but <em>K</em>-fold cross-validation is not, executing the function <code>accuracy.MC()</code> for the Monte-Carlo results should suffice. The results from <em>K</em>-fold cross-validation will be used to make membership probability plots.</p>
<hr />
</div>
<div id="identify-informative-loci" class="section level2">
<h2>Identify informative loci</h2>
<p>In some cases, using a subset of high <em>F<sub>ST</sub></em> loci may produce similar assignment accuracy as using all available loci. Identification of these loci could help reduce time and cost in preparing samples in the future and help identify loci that might be associated with functional genes.</p>
<p>The following function reads through the training locus file for each assignment test, counts the frequency of occurrence of each locus, and writes the results to a text file. This function should be run on the cross-validation results based on resampling high <em>F<sub>ST</sub></em> training loci (<code>loci.sample = &quot;fst&quot;</code>), rather than the randomly resampled loci (<code>loci.sample = &quot;random&quot;</code>), as the latter would be uninformative.</p>
<pre class="r"><code>check.loci(dir = &quot;Result-folder/&quot;, top.loci = 20)</code></pre>
<p>By default, this function outputs top 20 loci that are most frequently used as training loci (determined by locus <em>F<sub>ST</sub></em> value and proportions of your training loci) across your assignment tests, but you can instead specify the number of top training loci to be included.</p>
<p>When the function is executed, you will be prompted to choose which specific proportion of training individuals you would like to look up.</p>
<pre><code>## 3 levels of training individuals are found.
## Which levels would you like to check? (separate levels by a whitespace if multiple)
## Options: 0.5, 0.7, 0.9, or all
## enter here: (You will enter your answer here)</code></pre>
<p>The <em>F<sub>ST</sub></em> value calculated for a locus will differ depending on which subset of individuals was sampled for the training set. We recommend running the <code>check.loci()</code> function across all levels of proportion of training individuals to evaluate if the loci are consistently found to be informative.</p>
<p>The output file (<em>High_Fst_Locus_Freq.txt</em>) includes a list of locus names ordered by <em>F<sub>ST</sub></em> value (highest <em>F<sub>ST</sub></em> in the top row). The number in parentheses following each locus name indicates how many tests that locus appeared in that rank. A sample of output content is shown below.</p>
<pre><code>Loci occur in top 20 high Fst across all training data
top.1(1): Locus_171(360), 
top.2(1): Locus_442(360), 
top.3(1): Locus_475(360), 
top.4(1): Locus_481(360), 
top.5(1): Locus_696(360), 
top.6(1): Locus_697(360), 
top.7(1): Locus_729(360), 
top.8(1): Locus_745(360), 
top.9(1): Locus_812(360), 
top.10(1): Locus_941(360), 
top.11(1): Locus_992(360), 
top.12(5): Locus_113(248), Locus_114(76), Locus_115(24), Locus_320(8), Locus_139(4), 
top.13(7): Locus_245(240), Locus_181(72), Locus_147(24), Locus_115(8), Locus_560(8), Locus_137(4), Locus_160(4), </code></pre>
<p>The above results show that across our 360 tests, the top 11 highest <em>F<sub>ST</sub></em> loci are the same across all 360 tests. Four loci (<code>Locus_113, Locus_114, Locus_115, and Locus_320</code>) appear to be the 12th highest <em>F<sub>ST</sub></em> locus across the tests, and <code>Locus_113</code> occurs most frequently (248 out of 360 tests) in this rank.</p>
<hr />
<div id="reference-and-footnotes" class="section level4">
<h4>Reference and footnotes</h4>
</div>
</div>
<div class="footnotes">
<hr />
<ol>
<li id="fn1"><p>Rousset, F. (2008). genepop’007: A Complete Re-Implementation of the Genepop Software for Windows and Linux. <em>Molecular Ecology Resources</em> 8(1): 103–106. <a href="doi:10.1111/j.1471-8286.2007.01931.x" class="uri">doi:10.1111/j.1471-8286.2007.01931.x</a>.<a href="#fnref1">↩</a></p></li>
<li id="fn2"><p>The name order in the argument <code>pop.names</code> should match the group order in your GENEPOP file. For example, the first name, <code>pop_A</code>, in <code>pop.names=c(&quot;pop_A&quot;,&quot;pop_B&quot;,&quot;pop_C&quot;)</code> is the top first group (pop) of samples in the GENEPOP.<a href="#fnref2">↩</a></p></li>
<li id="fn3"><p>A low variance locus is one in which a single (major) allele occurs in most individuals, with an alternate (minor) allele occurring in only a few individuals. Removal of these low variance loci will help avoid the problem of a minor allele ending up being assigned to either only training or only test sets. For example, if 9 out of 10 individuals have the same genotype (e.g., AA, A is major allele) and only 1 individual has the minor allele (e.g., Aa, a is minor allele with 0.05 frequency), the locus will not help predict the group of individuals regardless of whether the rare Aa individual is assigned to a training or test set. Therefore, removal of low variance loci does not influence results but helps accelerate post analyses.<a href="#fnref3">↩</a></p></li>
<li id="fn4"><p>In this case, we have 614 alleles across 307 loci, meaning that every locus is biallelic (307 loci x 2 alleles = 614 alleles)<a href="#fnref4">↩</a></p></li>
<li id="fn5"><p>A column includes population names for each individual. Also be sure to include a column name in table header.<a href="#fnref5">↩</a></p></li>
</ol>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
