context("Test check.loci")

test_that("check loci from results generated by loci.sample=random",{
  expect_message(check.loci(dir="ResMCtest/"), "")
})

test_that("check loci from results generated by loci.sample=fst",{
  check.loci(dir="ResMCtestFst/")
  expect_true(file.exists("ResMCtestFst/High_Fst_Locus_Freq.txt"))
})
unlink("ResMCtestFst/High_Fst_Locus_Freq.txt")